version: '2'

services:
  reverse-proxy:
    image: monkeydri/reverse-proxy:latest
    # override CMD to pass docker hub build environment variables 
    command: ["sh", "-c", "/home/user/dockers/reverse-proxy/setup.sh ${EMAIL} ${URL} ${SUBDOMAINS} true ${SSH_PUBLIC_KEY} ${SSH_PRIVATE_KEY}"]
  sut:
    build: ./tests/
    environment:
      - EMAIL
      - URL
      - SUBDOMAINS
    depends_on:
      - reverse-proxy