version: '2'


services:
  reverse-proxy:
    image: monkeydri/reverse-proxy:latest
    environment:
      - EMAIL
      - URL
      - SUBDOMAINS
      - TIMBER_API_KEY
      - TIMBER_SOURCE_ID
      - TEST_MODE=true
      - SSH_PUBLIC_KEY
      - SSH_PRIVATE_KEY
    tty: true
  sut:
    build: ./tests/
    environment:
      - EMAIL
      - URL
      - SUBDOMAINS
    depends_on:
      - reverse-proxy