version: '2'


services:
  reverse-proxy:
    image: monkeydri/reverse-proxy:latest
    # env vars with no value are taken from the same variable in the shell in which Compose is run => docker hub build environment variables
    environment:
      - EMAIL
      - URL
      - SUBDOMAINS
      - LOGGLY_SUBDOMAIN
      - LOGGLY_USERNAME
      - TEST_MODE=true
      - SSH_PUBLIC_KEY
      - SSH_PRIVATE_KEY
  sut:
    build: ./tests/
    environment:
      - EMAIL
      - URL
      - SUBDOMAINS
      - LOGGLY_SUBDOMAIN
      - LOGGLY_USERNAME
    depends_on:
      - reverse-proxy