version: '3.5'

services:
  lets-encrypt:
    image: linuxserver/letsencrypt
    container_name: lets-encrypt
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PGID=1000 
      - PUID=1000
      - EMAIL="${EMAIL}"
      - URL="${URL}"
      - SUBDOMAINS="${SUBDOMAINS}"
      - VALIDATION=http
      - TZ=Europe/Paris
    volumes:
      - $PWD/config:/config
    networks:
      - nginx-net

networks:
  nginx-net:
   driver: bridge
